In [2]:
import pandas as pd
#sep='\t' 代表用Tab隔开,comment='!'代表跳过所有带感叹号的行
geo_df= pd.read_csv('GSE1009_series_matrix.txt',sep='\t',comment='!')

In [3]:
#看是否读取成功
geo_df.head()

      ID_REF  GSM15965  GSM15966  GSM15967  GSM15968  GSM15969  GSM15970
0    1000_at    3045.2    3076.5    3288.1    4870.6    2826.3    4982.3
1    1001_at     891.0     791.7    1351.1    2155.4    1882.9    2520.5
2  1002_f_at      11.6      59.8      40.5      60.5     104.3     329.4
3  1003_s_at     137.5     117.0     262.0     275.0     750.0     167.3
4    1004_at      69.5     241.1     287.1     529.1     456.8     956.9

In [4]:
#看最大值
geo_df.max()

ID_REF      AFFX-hum_alu_at
GSM15965           153176.0
GSM15966            91058.8
GSM15967            54187.0
GSM15968           388917.9
GSM15969           147664.7
GSM15970           131651.9
dtype: object

In [5]:
import numpy as np
#剔除第一列基因名(因为文字不能转对数),给剩下的数据加1,然后求Log2
log2_data = np.log2(geo_df.iloc[:,1:]+1)

In [6]:
#看转换后的数据
log2_data.head()

    GSM15965   GSM15966   GSM15967   GSM15968   GSM15969   GSM15970
0  11.572795  11.587543  11.683477  12.250180  11.465209  12.282886
1   9.800900   9.630631  10.400986  11.074409  10.879507  11.300067
2   3.655352   5.925999   5.375039   5.942515   6.718362   8.368070
3   7.113742   6.882643   8.038919   8.108524   9.552669   7.394891
4   6.139551   7.919459   8.170426   9.050121   8.838574   9.903731